### PR TITLE
Update formula to be human-readable

### PR DESCRIPTION
**Pull request by cjwilliams**
Improve the automatic generation of formula so the output is more human-readable

### CODE REVIEW

**Comment by cjwilliams** [comment]
@Katharine or @matthewtole if you wouldn't mind doing the honors...

The existing/public 3.0 pebble-sdk.rb has been updated in this PR using the modified pebble-sdk.rb.template file and the generator script.

**Comment by Katharine** [comment]
This looks like it needs some other change elsewhere?

**Comment by cjwilliams** [comment]
@Katharine, what other changes are you concerned about?

For this PR, the formatting of the output file has been changed (and the input template file as a required step). The sdk generator is handling the process of converting/updating, but I don't think the sdkgen PR should be a prerequisite for this format-only change (this repo should really be able to exist without knowledge of the mechanism that updates the formula, human or otherwise).

**Comment by Katharine** [comment]
You've changed what the template expects, but I can't see any corresponding change that would cause that to be filled in correctly. Is this template actually used? Would the thing using it still work if this were merged?

**Comment by cjwilliams** [comment]
pebble-sdk.rb.template is used by the SDK generator, and these specific changes to the template are used by https://github.com/pebble/pebblesdk-generator/blob/feature/add-homebrew-support/lib/BrewTap.py#L139-L142

The generator would still work because the updated pebble-sdk.rb in this PR was created with the generator using the pebble-sdk.rb.template file in this PR.

**Pull request merged**
